### PR TITLE
35-content-and-navbar-iteration-2

### PR DESCRIPTION
**Pull request by redblindbananaz**
-Creation of home button
-Active links for home, courses and profile
-Creation of 2 more courses title and description
-Cards styling
-Adjust each page layout and forms to feel unifrom
-Modification of courses model for logo image
-Addition of logo images
-Landing page content and addition image
-General styling of the overall application

### CODE REVIEW

**Comment by redblindbananaz** [comment]
Apart from the addition of the image model in Courses to add the logo, the rest is styling and moving things around, not much work on functionnalities applied

**Review by makikamiya — APPROVED** [review]
That's fantastic work, @redblindbananaz ! Everything looks so good. I really like the course cards. All runs smoothly. Happy to approve and merge.

**Review by makikamiya — APPROVED** [review]
Approving all changes and to merge this branch into master.

**Review by makikamiya — APPROVED** [review]

**Review by makikamiya — APPROVED** [review]

**Review by makikamiya — APPROVED** [review]
Happy to approve.

**Pull request merged**
